### ISSUE TITLE
instagram data issue

### ISSUE THREAD

**Issue by mirakoz** [Gladior-B-V/instagram-insights-connector#2]
<img width="1670" alt="image" src="https://user-images.githubusercontent.com/116177363/196701461-ea3ebef3-3356-4ed1-9f24-2af6c6ac0f0d.png">

**Comment by zoedufrenne** [comment]
Hi @mirakoz, I'm sorry that we didn't respond sooner. Do you still get this error? 
With just a date dimension, the table won't work, you need to add the caption to the table.

**Comment by mirakoz** [comment]
hi there,

Well, it's been a while since I'm not using it anymore. But I'll check it
asap.

Thank you for the information.

Kind regards,

Mirak Özoğlu
Digital Marketing | canias4.0
m: +90 531 723 1370 <905317231370>
[image: facebook icon] <https://www.facebook.com/mirak.miko.ozoglu> [image:
twitter icon] <https://twitter.com/themirak> [image: youtube icon]
<https://www.youtube.com/channel/UCjGqQGOzxaVZtxZBnwxaifg> [image: linkedin
icon] <https://www.linkedin.com/in/mirakozoglu/> [image: instagram icon]
<https://www.instagram.com/themirak>


zoedufrenne ***@***.***>, 4 Oca 2023 Çar, 16:42 tarihinde
şunu yazdı:
