### ISSUE TITLE
I can't connect a new data source

### ISSUE THREAD

**Issue by GeorginaAlcaraz** [Gladior-B-V/instagram-insights-connector#3]
Hi, when I try to connect a new source the page doesn't load.  When I click on Add new credential, it takes me to another page and doesn't load anything.
![Uploading Captura de Pantalla 2023-02-08 a la(s) 10.29.40.png…]()
<img width="1437" alt="Captura de Pantalla 2023-02-08 a la(s) 10 29 47" src="https://user-images.githubusercontent.com/123579191/217591572-5970defc-800a-4ab1-a97d-dd937cc6e7d3.png">

**Comment by zoedufrenne** [comment]
Hi @GeorginaAlcaraz,
From where did you add the new credential? Is it from the datahubapp.gladior.com or from Looker Studio?

**Comment by GeorginaAlcaraz** [comment]
Hi @zoedufrenne , I tried to do it on the data hub and on looker studio, I'm having that problem trying to connect an Instagram account.

**Comment by zoedufrenne** [comment]
Hi @GeorginaAlcaraz, Could you try it in an incognito venster? 
Do you have accounts connected to your Instagram account that also have a connection with a Facebook page?
