### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by seekerparkingdev** [Gladior-B-V/instagram-insights-connector#5]

**Comment by zoedufrenne** [comment]
HI @seekerparkingdev,

What is not working with the connector? 
Can you send us a screenshot and let us know in which step it doesn't work? Because I just tried it myself, and the connector still works.

**Comment by seekerparkingdev** [comment]
Hi! look at this, i was wrong, was Linkedin. 

The linkedin connector, no matter if it is a youtube link, a PDF, an image, likes, reactions and comments, catalogs them as Null. 
https://drive.google.com/drive/folders/1Hh8kdJHZmEo8bLORW0Sl2aWPVg-WLuSl?usp=sharing

**Comment by zoedufrenne** [comment]
Hi,
That's correct the linkedin insights connector only supports article, image or none. This is the standard in Linkedin. You can find the information here about the possible output: 
https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/share-on-linkedin?context=linkedin%2Fconsumer%2Fcontext  --> shareMediaCategory
