### ISSUE TITLE
Getting "No options were provided for "Instagram Business Account". Check if you have the correct account/rights." message since late june when trying to reconnect or add new instagram connections

### ISSUE THREAD

**Issue by eresfavolosx** [Gladior-B-V/instagram-insights-connector#6]
Greetings, 

I hope all is well! Since late June all of my Business Instagram accounts got disconnected and am unable to reconnect or add them again.  I am receiving the error message "No options were provided for "Instagram Business Account". Check if you have the correct account/rights.". There have been no changes to the permissions or the configuration of the Instagram Accounts. All the Instagram accounts are Business Accounts, Connected Properly to each Facebook Page, and I have admin rights to all the accounts. Please let me know if this case has any resolution. 

Thank you in advance,

**Comment by eresfavolosx** [comment]
Greetings, 

I hope all is well! I have an issue similar to the other case posted in this project, but it does not show the pages I had connected to Gladiator previously. The accounts literally will not show up in the drop-down menu to add the account. I have tried removing the connectors from Facebook, removing all the accounts from the Gladiator Platform, removing the Business Integration from Facebook, using different Facebook accounts with admin privileges, and nothing has been working. Please let me know if there is a resolution to this issue.

**Comment by zoedufrenne** [comment]
Hi @favolosoboricua ,

Is it possible to add the credential again in the Data hub app? (even when it's already connected. And when you connect to instagram, go back to the previous settings and select all the current profiles. There is been a change in Instagram with connecting to all accounts. By our account this was the fix!

![image](https://github.com/Gladior-B-V/instagram-insights-connector/assets/84766152/c6ecec27-cfd7-455b-b94c-37bd2784b135)

Please let me know if it worked!

**Comment by eresfavolosx** [comment]
Hi @zoedufrenne! Thank you for the quick response! Unfortunately, this method did not work, my past Instagram accounts are still not showing. The system only shows accounts that I have never added to the platform. Please let me know if there is another workaround.

**Comment by eresfavolosx** [comment]
By the way, I am also having the same issue with the Facebook Insights connector. THe workaround did not work either.

**Comment by eresfavolosx** [comment]
Hi @zoedufrenne! I hope you had a great weekend! Where you able to check into this? Thank you in advance.
